default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: backend_helpjuicetest_development
  username: postgres
  password: admin

test:
  <<: *default
  database: backend_helpjuicetest_test
  username: postgres
  password: admin

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
